### PR TITLE
chore: add vander as daskom1337 community member

### PR DESCRIPTION
**Pull request by VANduts**
I made ascii art and commited to development branch. 
I edited people.js with my own profile.

### CODE REVIEW

**Review by fakhrip — CHANGES_REQUESTED** [review]
Haven't tried it yet on the website but i can tell without even trying it that your ascii art is way too big for our website XD, you have to change it first to a much smaller one vander, probably around 95x95 is the max characters you can use for that one

**Comment by VANduts** [comment]
Thank you, i will try to change the art

**Review by fakhrip — APPROVED** [review]
image

Cool, congratulations for finishing the git and github course vander, see you on the next one, and welcome to our community! 🥳

**Comment by VANduts** [comment]
Thank you very much, i hope to learns lots from this community

**Pull request merged**
