### PR TITLE
chore: add Reynaldhi as daskom1337 community member

### PR DESCRIPTION
**Pull request by UnknownVisuals**
- Creating new html file named "rey.html"
- Adding Reynaldhi ascii art to rey.html
- Adding Reynaldhi profile to peoples.js

### CODE REVIEW

**Comment by UnknownVisuals** [comment]
Still can't find it :'v

**Comment by fakhrip** [comment]
Ohh thats weird! turns out Github changed its feature (again XD) https://stackoverflow.com/questions/57946787/cant-add-a-reviewer-for-github-pull-request, sorry for this, i will add you as a collaborator first and then will ping you back so you can check if then you can add reviewer or not

**Comment by fakhrip** [comment]
Okay now i have sent you the invitation @UnknownVisuals, you should accept it first, and then test if you can add reviewer or not, thanks!

**Comment by UnknownVisuals** [comment]
[SOLVED]

After accepting the invitation, the button shows up!
Thank you @fakhrip for the guidance (ﾉ◕ヮ◕)ﾉ

**Comment by fakhrip** [comment]
Cool!, now as you can see, unfortunately your ascii art is too big that everyone wont be able to see your data rey, so you have to change this first, commit and push it again to the development branch in your own forked repository and then it will automatically be updated to this current pull request

Make sure your ascii art only have maximum of 95 characters for the width and 95 characters for the height, so it will roughly be 95x95 characters max

image

**Review by fakhrip — CHANGES_REQUESTED** [review]
Change the ascii art first according to the above chat 👍

**Comment by UnknownVisuals** [comment]
I fixed the ASCII art resolution on "rey.html", you may have a look again.

**Review by fakhrip — APPROVED** [review]
image

Congratulations on finishing the git and github course once again rey! and welcome to our community 🥳

**Pull request merged**
